# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29006cf735ac63ee713f774bbb239e24afc24a3909306ba5b727c46f33e8e9bb6d3fdc0fc8c9c481aefc34727378a03405c4a4696de12f03ebc53222d3043172

test:
  secret_key_base: 1d39167a29db238f46de1bc08139efd9f5ead202dcc132c8cd5ed1246d4195765cc481fcc05bf3fc3807986002bd71d7ea9dadc3c83a847c058adc2c73929a48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
